services:
  - type: web
    name: telegram-webhook-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: CHANNEL_ID
        value: -1001763041158
      - key: ADMIN_USER_ID
        value: "7848870377"
